Fix undefined reference to tensor destructor and clean up
Fix was possible by changing from cc_test to tf_cc_test in BUILD file.
Also undefined reference to DlModelHelper::CreateTensorFromImage still persists, hence last unit test is still disabled!